<?php

namespace SharengoCore\Entity\Repository;

/**
 * AuthorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllAuthorities()
    {
        $countries = $this->createQueryBuilder('c')
            ->select('c.code, c.name')
            ->getQuery();

        return $countries->getResult();
    }
}
