<?php

namespace SharengoCore\Entity\Repository;

/**
 * CardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardsRepository extends \Doctrine\ORM\EntityRepository
{
    public function ajaxCardCodeAutocomplete($q)
    {
        $em = $this->getEntityManager();
        $dql = 'SELECT c FROM \SharengoCore\Entity\Cards c ' .
               'WHERE c.isAssigned = false AND c.assignable = true AND (LOWER(c.rfid) LIKE :value OR LOWER(c.code) LIKE :value)';

        $query = $em->createQuery();

        $query->setParameter('value', strtolower("%" . $q . "%"));
        $query->setDql($dql);
        return $query->getResult();
    }

    public function getLastRfid()
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT c.rfid FROM \SharengoCore\Entity\Cards c ORDER BY c.rfid DESC';

        $query = $em->createQuery($dql);
        $query->setMaxResults(1);

        return $query->getOneOrNullResult();
    }

    public function getTotalCards()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT COUNT(c.rfid) FROM \SharengoCore\Entity\Cards c');
        return $query->getSingleScalarResult();
    }
}
