<?php

namespace SharengoCore\Entity\Repository;

/**
 * CardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardsRepository extends \Doctrine\ORM\EntityRepository
{
    public function ajaxCardCodeAutocomplete($q)
    {
        $em = $this->getEntityManager();
        $dql = 'SELECT c FROM \SharengoCore\Entity\Cards c ' .
               'WHERE c.isAssigned = false AND (LOWER(c.rfid) LIKE :value OR LOWER(c.code) LIKE :value)';

        $query = $em->createQuery();

        $query->setParameter('value', strtolower("%" . $q . "%"));
        $query->setDql($dql);
        return $query->getResult();
    }
}
