<?php

namespace SharengoCore\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarsBonusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsBonusHistoryRepository extends EntityRepository
{
    public function deleteOldRecord($date){
        $em = $this->getEntityManager();

        $dql = "DELETE  
        FROM \SharengoCore\Entity\CarsBonusHistory cbh 
        WHERE cbh.insertedTs < :date ";

        $query = $em->createQuery($dql);
        $query->setParameter('date', $date);

        return $query->getResult();
    }
}
