<?php

namespace SharengoCore\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarsBonusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsBonusRepository extends EntityRepository
{
    public function findByPLate($plate){
        $em = $this->getEntityManager();

        $dql = "SELECT c
        FROM \SharengoCore\Entity\CarsBonus c
        WHERE c.plate = :plate ";

        $query = $em->createQuery($dql);
        $query->setParameter('plate', $plate);

        return $query->getResult();
    }
}
