<?php

namespace SharengoCore\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarsBonusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsBonusHistoryRepository extends EntityRepository
{
    
}
