<?php

namespace SharengoCore\Entity\Repository;

/**
 * CarsConfigurationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsConfigurationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTotalCarsConfigurations()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT COUNT(cc.id) FROM \SharengoCore\Entity\CarsConfigurations cc');
        return $query->getSingleScalarResult();
    }
}
