<?php

namespace SharengoCore\Entity\Repository;

/**
 * CarsInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsInfoRepository extends \Doctrine\ORM\EntityRepository
{
    
}
