<?php

namespace SharengoCore\Entity\Repository;

/**
 * CarDemagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsDamagesRepository extends \Doctrine\ORM\EntityRepository
{

}
