<?php

namespace SharengoCore\Entity\Repository;

use Doctrine\ORM\Query\ResultSetMapping;

/**
 * CarsConfigurationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsConfigurationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTotalCarsConfigurations()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT COUNT(cc.id) FROM \SharengoCore\Entity\CarsConfigurations cc');
        return $query->getSingleScalarResult();
    }

    public function findById($id)
    {
        $em = $this->getEntityManager();
        $dql = 'SELECT cc
            FROM \SharengoCore\Entity\CarsConfigurations cc
            WHERE cc.id = :id';

        $query = $em->createQuery($dql);
        $query->setParameter('id', $id);

        return $query->getResult();
    }
}
