<?php

namespace SharengoCore\Entity\Repository;

/**
 * ConfigurationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param      $slug
     * @param null $arrayResult
     *
     * @return array
     */
    public function findBySlug($slug, $arrayResult = null)
    {
        $em = $this->getEntityManager();
        $dql = 'SELECT c FROM \SharengoCore\Entity\Configurations c ' .
                'WHERE c.slug = :slug ORDER BY c.id ASC';

        $query = $em->createQuery();
        $query->setParameter('slug', $slug);
        $query->setDql($dql);

        if(!is_null($arrayResult) && $arrayResult == true) {
            return $query->getArrayResult();
        }

        return $query->getResult();
    }
}
