<?php

namespace SharengoCore\Entity\Repository;

/**
 * CustomersBonusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomersBonusRepository extends \Doctrine\ORM\EntityRepository
{
}
