<?php

namespace SharengoCore\Entity\Repository;

/**
 * FreeFaresRepository
 *
 * This class was generated by me. Add your own custom
 * repository methods below.
 */
class FreeFaresRepository extends \Doctrine\ORM\EntityRepository
{
}
