<?php

namespace SharengoCore\Entity\Repository;

/**
 * languagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguagesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param null $selectedLanguage
     * @return array
     */
    public function getAllLanguages($selectedLanguage = null)
    {
        if(is_null($selectedLanguage)) {
            $selectedLanguage ='Italiano';
        }

        $languages = $this->createQueryBuilder('l')
            ->select('l.code, l.name')
            ->orderBy('l.name')
            ->getQuery();

        // Move the element with 'l.name' = $selectedLanguage to the first place
        $result = $languages->getResult();

        for ($i=0; $i<count($result); $i++) {
            if ($result[$i]['name'] == $selectedLanguage) {
                $resultTmp = array();
                $resultTmp[0] = $result[$i];
                // Add the elements before and after the $i index
                $result = array_merge($resultTmp, array_slice($result, 0, $i, true),
                    array_slice($result, $i+1, count($result)-$i, true));
                break;
            }
        }

        return $result;
    }

}
