<?php

namespace SharengoCore\Entity\Repository;

use Doctrine\ORM\Query\ResultSetMapping;

/**
 * NotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTotalNotifications()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT COUNT(n.id) FROM \SharengoCore\Entity\Notifications n');
        return $query->getSingleScalarResult();
    }
}
