<?php

namespace SharengoCore\Entity\Repository;

/**
 * PromoCodesOnceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoCodesOnceRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByPromoCode($promoCode) {
        $dql = 'SELECT pco FROM \SharengoCore\Entity\PromoCodesOnce pco ' .
                'WHERE pco.promocode = :promocode';

        $em = $this->getEntityManager();
        $query = $em->createQuery($dql);
        $query->setParameter('promocode', $promoCode);

        return $query->getOneOrNullResult();
    }

}
