<?php

namespace SharengoCore\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PromoCodesInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoCodesInfoRepository extends EntityRepository
{
    public function findById($id) {
        $dql = 'SELECT pci FROM \SharengoCore\Entity\PromoCodesInfo pci ' .
                'WHERE pci.id = :id';

        $em = $this->getEntityManager();
        $query = $em->createQuery($dql);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }
}