<?php

namespace SharengoCore\Entity\Repository;

use SharengoCore\Entity\Customers;

/**
 * PromoCodesOnceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoCodesOnceRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByPromoCode($promoCode) {
        $dql = 'SELECT pco FROM \SharengoCore\Entity\PromoCodesOnce pco ' .
                'WHERE pco.promocode = :promocode';

        $em = $this->getEntityManager();
        $query = $em->createQuery($dql);
        $query->setParameter('promocode', $promoCode);

        return $query->getOneOrNullResult();
    }

    public function findByPromoCodeStartWith($promoCode) {
        $dql = 'SELECT pco FROM \SharengoCore\Entity\PromoCodesOnce pco ' .
                'WHERE pco.promocode LIKE :promocode';

        $em = $this->getEntityManager();
        $query = $em->createQuery($dql);
        $query->setParameter('promocode', $promoCode . '%');

        return $query->getResult();
    }

    public function findByPromoCodeByCustomer(Customers $customer) {
        $dql = 'SELECT pco FROM \SharengoCore\Entity\PromoCodesOnce pco ' .
                'WHERE pco.customer = :customer';

        $em = $this->getEntityManager();
        $query = $em->createQuery($dql);
        $query->setParameter('customer', $customer);

        return $query->getResult();
    }

}
