<?php

namespace SharengoCore\Entity\Repository;

/**
 * PromoCodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoCodesRepository extends \Doctrine\ORM\EntityRepository
{

    public function getActivePromoCode($promoCode) {

        $em = $this->getEntityManager();

        $dql = 'SELECT pc
                FROM \SharengoCore\Entity\Promocodes pc
                JOIN pc.promocodesinfo pci
                WHERE pc.promocode LIKE :promocode
                AND pc.active = true
                AND pci.active = true';

        $query = $em->createQuery($dql);
        $query->setParameter('promocode', $promoCode);

        return $query->getOneOrNullResult();

    }

}
