<?php

namespace SharengoCore\Entity\Repository;

/**
 * PromoCodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoCodesRepository extends \Doctrine\ORM\EntityRepository
{
}
