<?php

namespace SharengoCore\Entity\Repository;

/**
 * PromoCodesInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoCodesInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
