<?php

namespace SharengoCore\Entity\Repository;

/**
 * ReservationsArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationsArchiveRepository extends \Doctrine\ORM\EntityRepository
{
}
