<?php

namespace SharengoCore\Entity\Repository;

use SharengoCore\Entity\SafoPenalty;

/**
 * TripsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SafoPenaltyRepository extends \Doctrine\ORM\EntityRepository {

    public function countTotalFinesComplete()
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT COUNT(sp) FROM SharengoCore\Entity\SafoPenalty sp ' .
                'WHERE   sp.complete = TRUE '
                ;
                

        $query = $em->createQuery($dql);

        return $query->getSingleScalarResult();
    }
    
    public function getFinesBetweenDate($from, $to) {
        $em = $this->getEntityManager();

        $dql = 'SELECT sp.id FROM SharengoCore\Entity\SafoPenalty sp ' . 
                'WHERE sp.customer IS NOT NULL ' .
                'AND sp.trip IS NOT NULL ' .
                'AND sp.complete = TRUE ' .
                'AND sp.car IS NOT NULL ' .
                'AND sp.insertTs >= :from ' .
                'AND sp.insertTs < :to ' .
                'AND sp.charged = FALSE ' .
                'ORDER BY sp.id ';
        
        $query = $em->createQuery($dql);
        $query->setParameter('from', $from);
        $query->setParameter('to', $to);

        return $query->getResult();
    }
}
