<?php

namespace SharengoCore\Entity\Repository;

use SharengoCore\Entity\SafoPenalty;

/**
 * TripsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SafoPenaltyRepository extends \Doctrine\ORM\EntityRepository {

    public function countTotalFines()
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT COUNT(sp) FROM SharengoCore\Entity\SafoPenalty sp';

        $query = $em->createQuery($dql);

        return $query->getSingleScalarResult();
    }
}
