<?php

namespace SharengoCore\Entity\Repository;

/**
 * UpdateCarsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpdateCarsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastUpdateByPlate($plate)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT uc FROM \SharengoCore\Entity\UpdateCars uc WHERE uc.carPlate = :plate ORDER BY uc.update DESC");
        $query->setParameter('plate', $plate);
        $query->setMaxResults(1);

        return $query->getOneOrNullResult();
    }
}
