<?php

namespace SharengoCore\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEventsRepository extends EntityRepository
{
}