<?php

namespace SharengoCore\Entity\Repository;

/**
 * WebuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebuserRepository extends \Doctrine\ORM\EntityRepository
{
}
