<?php

namespace SharengoCore\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WebuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebuserRepository extends EntityRepository
{
    public function getTotalUsers()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT COUNT(u.id) FROM \SharengoCore\Entity\Webuser u');
        return $query->getSingleScalarResult();
    }
}
