<?php

namespace SharengoCore\Entity\Repository;

/**
 * ZoneAlarmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneAlarmsRepository extends \Doctrine\ORM\EntityRepository
{
}
