<?php

namespace SharengoCore\Entity\Repository;

/**
 * ZoneGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneGroupsRepository extends \Doctrine\ORM\EntityRepository
{
}
