<?php

namespace SharengoCore\Entity\Repository;

/**
 * ZonePricesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZonePricesRepository extends \Doctrine\ORM\EntityRepository
{
}
