<?php

namespace SharengoCore\Entity\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
use SharengoCore\Entity\Zone;

/**
 * ZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneRepository extends \Doctrine\ORM\EntityRepository
{
    public function findZonesWithMapCoords($showHidden) {

        $rsm = new ResultSetMapping;
        $rsm->addEntityResult('SharengoCore\Entity\Zone', 'z');
        $rsm->addFieldResult('z', 'id', 'id');
        $rsm->addFieldResult('z', 'name', 'name');
        $rsm->addFieldResult('z', 'area_invoice', 'areaInvoice');
        $rsm->addFieldResult('z', 'area_use', 'areaUse');

        $em = $this->getEntityManager();
        $query = $em->createNativeQuery('SELECT id, name, ST_AsGeoJSON(area_invoice) as area_invoice, ST_AsGeoJSON(area_use) as area_use FROM zone'.( $showHidden == true ? '' : ' WHERE hidden = FALSE' ), $rsm);

        return $query->getResult();
    }
}
