<?php

namespace SharengoCore\Entity\Repository;

/**
 * ZoneBonusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneBonusRepository extends \Doctrine\ORM\EntityRepository
{
}
